### ISSUE TITLE
Raspberry - No audio gateway is connected

### ISSUE THREAD

**Issue by ferbass** [littlecraft/phony#8]
I'm trying to run the cranky sample on Raspberry but I'm having some problem to send commands from the command line when try to dial or send voice command

```
(phony) voice
org.freedesktop.DBus.Python.Exception: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/phony/examples/cranky/debug.py", line 32, in BeginVoiceDial
    self._headset.initiate_call()
  File "/usr/local/lib/python2.7/dist-packages/phony/base/log.py", line 112, in call_wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/phony/headset.py", line 115, in initiate_call
    raise Exception('No audio gateway is connected')
Exception: No audio gateway is connected
```

I'm using this usb audio adapter
https://www.amazon.co.jp/gp/product/B00OJ5AV8I/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

Any idea?

Thank you in advanced

**Comment by ferbass** [comment]
Got it working after install pulseaudio with the follow instructions

https://raspberrypi.stackexchange.com/questions/639/how-to-get-pulseaudio-running

```
sudo apt-get install pulseaudio pulseaudio-module-zeroconf alsa-utils avahi-daemon

To enable ALSA:

sudo modprobe snd-bcm2835                      # load module for single boot
echo "snd-bcm2835" | sudo tee -a /etc/modules  # load module for persistance

To set up networking:

sudo vim /etc/pulse/default.pa
and uncomment the lines:

load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1;192.168.0.0/16
load-module module-zeroconf-publish
To start the pulseaudio server, use:

pulseaudio -D
You should be able to test that it works by playing a wav file with paplay (sudo apt-get install pulseaudio-utils), and also over the network by selecting the sink in your system's sound control panel.

You might be also be able to set up in system-wide mode with:

sudo pulseaudio --system 
```
